# Artificial Neural Networks for Regression

## Problem Statement: Prediction of energy output from Combined Cycle Power Plant Dataset

This is an open dataset from the Machine Learning Repository of Center for Machine Learning and Intelligent Systems at the University of California, Irvine [(Dataset Link)](https://archive.ics.uci.edu/ml/datasets/combined+cycle+power+plant). The dataset contains 9568 data points that have been collected from a Combined Cycle Power Plant over 6 years (2006-2011). During this period, the power plant was set to work with a full load. Features consist of hourly average ambient variables Ambient Temperature (AT), Ambient Pressure (AP), Relative Humidity (RH), and Exhaust Vacuum (V) to predict the net hourly electrical energy output (PE) of the plant.

Features consist of hourly average ambient variables
- Ambient Temperature (AT) in the range 1.81°C to 37.11°C
- Exhaust Vacuum (V) in the range 25.36-81.56 cm Hg
- Ambient Pressure (AP) in the range 992.89-1033.30 millibar
- Relative Humidity (RH) in the range 25.56% to 100.16%
- Net hourly electrical energy output (PE) 420.26-495.76 MW

The averages are taken from various sensors located around the plant that record the ambient variables every second. The variables are given without normalization.

Given the attributes, our objective is to predict Net hourly electrical energy output (PE).

![ANN for Regression](ANN-for-Regression-01.PNG)

**Important Note 1:** This dataset contains no missing data and no categorical data. Hence, those steps for Data Preprocessing (Taking care of missing data and Encoding categorical data) are not required before starting Training of the Model.

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('combined_cycle_power_plant.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Taking care of missing data

Here we have no missing data in the dataset.

**Important Note:** If missing data acounts for less than 1% of dataset, we can discard them. But in all other cases, we have to replace missing data. Missing data can be replaced with either mean, median, most frequent data or with a constant using `SimpleImputer` from `sklearn.impute`. Other solutions include `IterativeImputer`, `KNNImputer` and `MissingIndicator`.



### Encoding categorical data

If any of the columns have categorical data, you should apply Encoding to convert them into numerical data. Encoding should be

*   One Hot Encoding if you know there is no ordered relationship in your categorical variable (eg: Country, State etc.)
*   Label Encoding if there is an ordered relationship (eg: Position Levels in a company, Purchase Decisions etc.)



Here we have no categorical data in the dataset and hence encoding is not required.

### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

Feature Scaling is compulsory for Deep Learning. It is so fundamental that we have to do Feature Scaling even for the columns that already have values in the target range aimed by Feature Scaling.

## Part 2 - Building the ANN

### Initializing the ANN

ANNs can be of 2 types

*   A Sequence of Layers
*   A Computational Graph

Our ANN is a Sequence of Layers as depicted in the figure.



In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

We don't need to specify the Input Layer explicitly since that will be automatically taken cared by Tensorflow. Since we have dense connections between Input Layer and first Hidden Layer (fully connected), we add `Dense` layer to our `ann` with Rectifier Activation Function.

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

Binary Classification => `activation='sigmoid'`

Non-binary Classification => `activation='softmax'`

Regression => `activation=None` (Default argument)

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

Updation of weights is done using Stochastic Gradient Descent method during Back Propagation. This is performed by `optimizer` tool. Here we use `'adam'` optimizer (highly recommended for Stochastic Gradient Descent).

For Regression, we use `'mean_squared_error'` as loss function.

In [11]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 785us/step - loss: 55765.2410
Epoch 2/100
240/240 [==============================] - 0s 810us/step - loss: 409.6603
Epoch 3/100
240/240 [==============================] - 0s 785us/step - loss: 361.7311
Epoch 4/100
240/240 [==============================] - 0s 833us/step - loss: 313.1711
Epoch 5/100
240/240 [==============================] - 0s 828us/step - loss: 254.2927
Epoch 6/100
240/240 [==============================] - 0s 750us/step - loss: 210.8140
Epoch 7/100
240/240 [==============================] - 0s 795us/step - loss: 164.4499
Epoch 8/100
240/240 [==============================] - 0s 766us/step - loss: 120.6553
Epoch 9/100
240/240 [==============================] - 0s 732us/step - loss: 90.6361
Epoch 10/100
240/240 [==============================] - 0s 731us/step - loss: 65.4843
Epoch 11/100
240/240 [==============================] - 0s 751us/step - loss: 53.8461
Epoch 12/100
240/240 [==============================]

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [13]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[433.46 431.23]
 [464.8  460.01]
 [468.38 461.14]
 ...
 [475.62 473.26]
 [442.13 438.  ]
 [461.52 463.28]]
