# Support Vector Regression (SVR)

## Intuition behind Support Vector Regression

Instead of finding the best fitting line as in Linear Regression, in SVR we focus on finding the best fitting tube. The tube is actually a regression line with an error $\epsilon$ that we disregard. Thus, we create an $\epsilon$-insensitive tube, disregard errors due to all the points within the tube and instead focus on points outside the tube. We have to find the narrowest tube with minimum prediction error for the training data. We fit the tube such that these two conditions are satisfied:

1.   the width of the tube is a minimum
2.   the sum of the errors due to outer points (called "Slack Variables" $\xi_i$ and $\xi_i^*$) is a minimum.

![Support Vector Regression Intuition](Support-Vector-Regression-Intuition-01.PNG)

All points in this space can be treated as vectors. Since points corresponding to Slack Variables are supporting or dictating the structure or formation of this tube, such vectors are called Support Vectors and the regression method is called Support Vector Regression.

**Important Note:** Here we have discussed Linear Support Vector Regression Model. But SVR can be applied to non-linear cases also. Non-linear SVR is a bit complex and will be discussed in the future once we get a hold of SVM (Support Vector Machine) and Kernel SVM sections.

## Problem Statement

We have a dataset containing salary data of employees of different position levels (1 to 10) in a company. Here,


*   Independent Variable/Feature = Level
*   Dependent/Target Variable = Salary

Here, Salary and Level have non-linear relationship between them. We want to build a model that can predict the salary given the level of an employee. Since we have a non-linear dataset, this problem can be formulated as a Polynomial Linear Regression problem.

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [4]:
print(y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [5]:
# Convert y from 1D vector to 2D array (since StandardScaler Class expects a 2D array as input)
y = y.reshape(len(y), 1)

In [6]:
print(y)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


## Taking care of missing data

Here we have no missing data in the dataset.

**Important Note:** If missing data acounts for less than 1% of dataset, we can discard them. But in all other cases, we have to replace missing data. Missing data can be replaced with either mean, median, most frequent data or with a constant using `SimpleImputer` from `sklearn.impute`. Other solutions include `IterativeImputer`, `KNNImputer` and `MissingIndicator`.



## Encoding categorical data

In the dataset, you can see that 'Position' column is effectively encoded in 'Level' column. Hence, 'Position' column is redundant and is not included in the Feature Matrix X.

## Splitting the dataset into the Training set and Test set

Here, we want to predict the salary for Employee Level (which is a continuous real value that varies from 1 to 10). Hence we want the data for all levels from 1 to 10 for accurate prediction. Hence, in this scenario, we are not splitting the dataset.

## Feature Scaling

In Linear Regression Models, even if some features have higher values than others, the coefficients will compensate to put every feature on the same scale. But for Support Vector Regression Models, there is no explicit relationship between Features and Target Variable that can be represented using coefficients. Hence, Feature Scaling is required.

Here, Feature Scaling should be applied for both Feature (`Level`) and Target Variable (`Salary`).

In [7]:
from sklearn.preprocessing import StandardScaler
# Use different StandardScaler objects for X and y (since both have diff mean and std deviations)
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [8]:
print(X)

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]


In [9]:
print(y)

[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]


## Training the SVR model on the whole dataset

In [10]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf') # Build SVR Model with Gaussian Radial Basis Function Kernel
regressor.fit(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

## Predicting a new result

Since we have done Feature Scaling on X and y, we need to provide scaled input to perform a single prediction and we get scaled output. Inverse Transformation should be performed on this scaled output in order to yield an output in the original scale.

In [11]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])))

array([170370.0204065])

## Visualising the SVR results

## Visualising the SVR results (for higher resolution and smoother curve)